name = "MyDemoPackage"
uuid = "91b3a4e1-0a4f-4449-9a30-ef9728f1b0bc"
authors = ["debruine <debruine@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
